//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier_Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID_Employee { get; set; }
        public int ID_User { get; set; }
        public string SurnameEmployee { get; set; }
        public string NameEmployee { get; set; }
        public string PatronicEmployee { get; set; }
        public string PhoneNumber { get; set; }
        public string PasportData { get; set; }
        public string AddresEmployee { get; set; }
        public string Datebirth { get; set; }
    
        public virtual UserSystem UserSystem { get; set; }

        public int IdPost
        {
            get
            {
                return this.UserSystem.ID_Post;
            }
        }
        public string LoginUser
        {
            get
            {
                return this.UserSystem.Login;
            }
        }
        public string PasswordUser
        {
            get
            {
                return this.UserSystem.Password;
            }
        }
    }
}
