//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier_Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductMaterials = new HashSet<ProductMaterials>();
            this.Shipment = new HashSet<Shipment>();
        }
    
        public int ID_Materials { get; set; }
        public int ID_Unit { get; set; }
        public int ID_TypeMaterial { get; set; }
        public string NameMaterial { get; set; }
        public int CountOnStok { get; set; }
        public string Warranty { get; set; }
        public decimal CostOfUnit { get; set; }
    
        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual Uints Uints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterials> ProductMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipment { get; set; }
    }
}
