//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier_Practice
{
    using System;
    using System.Collections.Generic;
    using System.Reflection.Emit;

    public partial class Shipment
    {
        public int ID_Materials { get; set; }
        public int ID_Suppliner { get; set; }
        public System.DateTime DateShipment { get; set; }
        public int CountMaterial { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Suppliner Suppliner { get; set; }

        public string Fullnamesupp
        {
            get
            {
                return $"{Suppliner.NameSuppliner}";
            }
        }
    }
}
